apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ntjarvo1l-nodejs 
  janus-idp.io/tekton: ntjarvo1l-nodejs
  backstage.io/kubernetes-id: ntjarvo1l-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ntjarvo1l-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml